apiVersion: v2
name: podinfo
description: Podinfo Helm chart for Kubernetes
type: application
version: 6.11.1-bb.0
appVersion: 6.11.1
annotations:
  bigbang.dev/maintenanceTrack: bb_maintained
  bigbang.dev/applicationVersions: |
    - Podinfo: 6.11.1
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://github.com/stefanprodan/podinfo/releases)
    - [and our upstream application release notes here](https://github.com/stefanprodan/podinfo/releases)
dependencies:
  - name: podinfo
    alias: upstream
    version: "6.11.1"
    repository: "https://stefanprodan.github.io/podinfo"
  - name: bb-common
    version: "0.14.1"
    repository: oci://registry1.dso.mil/bigbang
  - name: gluon
    repository: oci://registry1.dso.mil/bigbang
    version: 0.9.8