apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ .Release.Name }}-redis-protected-mode
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  rules:
    - name: disable-redis-protected-mode
      match:
        any:
          - resources:
              kinds:
                - ConfigMap
              names:
                - "*-redis"
      mutate:
        patchStrategicMerge:
          data:
            redis.conf: |-
              {{`{{request.object.data."redis.conf"}}`}}
              protected-mode no